# Generated by Django 4.2.6 on 2024-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Stationary', 'Stationary'), ('Food', 'Food'), ('Electronics', 'Electronics')], max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
